### ISSUE TITLE
Misleading note in readme

### ISSUE THREAD

**Issue by JamesBond0014** [dilevin/CSC2549-a4-cloth-simulation#13]
In the section under the equation for dsij there is a note that says: 

The second thing to keep in mind is that all derivatives wrt to s2 are zero (it never changes, it's always 0).

which is no longer accurate

**Comment by dilevin** [comment]
From the Readme.md displayed on the GitHub:

<img width="867" alt="image" src="https://user-images.githubusercontent.com/1903521/99204181-d6ecb180-2782-11eb-8cd9-1b0b5ad11ab1.png">


Where are you seeing this statement ?

**Comment by JamesBond0014** [comment]
whoops, my readme must be outdated, I just pulled and no longer see it.
